name: Lint
on:
  - push
jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '19'
      - run: npm install
      - run: npm run lint